#pragma config(Sensor, in1,	potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in8,	lightSensor,	sensorReflection)
#pragma config(Motor,  port3,       	light,     	tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port6,       	wheelMotor,	tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,       	servo,     	tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard           	!!*//

task main()
{
  	turnFlashlightOn();
  	 
    int P_30d_threshold = 1000;
    
    int P_f_threshold = 2000;

    int BLK_L_threshold = 900;
    
    int WHT_L_threshold = 550;
    
    SensorValue[in1] = 0;
    
    int P_startPoint = SensorValue[in1];
    
    for (;;){
  	 
    
		wait1Msec(1000);
		
		while( SensorValue[in1] < P_30d_threshold) {
			startMotor(wheelMotor, -20);
		}
		
		stopMotor(wheelMotor);
		
		wait1Msec(200);
		
		int sensorVal = SensorValue[in8];
		
		int servoVal;
		
		if (sensorVal > BLK_L_threshold){
			servoVal = -125;
		}
		else if (sensorVal > WHT_L_threshold){
			servoVal = 0;
		}
		else {
			servoVal = 125;
		}
		
		for (int i = 0; i < 10000; i++){
			setServo(servo, servoVal);
		}
		
		
		
		while( SensorValue[in1] < P_f_threshold) {
			startMotor(wheelMotor, -20);
			setServo(servo, servoVal);
		}
		
		stopMotor(wheelMotor);
		
		wait1Msec(2000);
		
		setServo(servo, servoVal);
		
		
		
		
		
		while( SensorValue[in1] > P_startPoint) {
			startMotor(wheelMotor, 20);
		}
		
		stopMotor(wheelMotor);
		
		wait1Msec(200);

    }
    
}
	
